# Generated by Django 3.2.7 on 2022-04-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('area', models.DecimalField(decimal_places=5, default='', max_digits=50)),
                ('season', models.CharField(max_length=50)),
                ('crop_name', models.CharField(max_length=50)),
            ],
        ),
    ]
